on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "The version of the fake Swift package registry to release"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: |
          deno task compile
          gh release create \
            ${{ github.event.inputs.version }} \
            --title "Release ${{ github.event.inputs.version }}" \
            --generate-notes \
            .build/fake-swift-package-registry

